export default {
  Ribbon: '[data-cy="Ribbon"]',
  TopBar: '[data-cy="TopBar"]',
  
  QuickAccessToolbar: '[data-cy="QuickAccessToolbar"]',
  QAT_toggle_QAD: '[data-cy="QuickAccessToolbar-toggle-QuickAccessDropdown"]',
  QAT_el_save: '[data-cy="QuickAccessToolbar-element-save"]',
  QAT_el_undo: '[data-cy="QuickAccessToolbar-element-undo"]',
  QAT_el_redo: '[data-cy="QuickAccessToolbar-element-redo"]',
  QAT_el_open: '[data-cy="QuickAccessToolbar-element-open"]',
  QAT_el_email: '[data-cy="QuickAccessToolbar-element-email"]',
  QAT_el_newFile: '[data-cy="QuickAccessToolbar-element-newFile"]',
  QAT_el_print: '[data-cy="QuickAccessToolbar-element-print"]',
  QAT_el_printPreview: '[data-cy="QuickAccessToolbar-element-printPreview"]',
  
  QuickAccessDropdown: '[data-cy="QuickAccessDropdown"]',
  QAD_toggle_Ribbon: '[data-cy="QuickAccessDropdown-toggle-Ribbon"]',
  QAD_toggle_position: '[data-cy="QuickAccessDropdown-toggle-position"]',
  QAD_toggle_el_save: '[data-cy="QuickAccessDropdown-toggle-element-save"]',
  QAD_toggle_el_undo: '[data-cy="QuickAccessDropdown-toggle-element-undo"]',
  QAD_toggle_el_redo: '[data-cy="QuickAccessDropdown-toggle-element-redo"]',
  QAD_toggle_el_open: '[data-cy="QuickAccessDropdown-toggle-element-open"]',
  QAD_toggle_el_email: '[data-cy="QuickAccessDropdown-toggle-element-email"]',
  QAD_toggle_el_newFile: '[data-cy="QuickAccessDropdown-toggle-element-newFile"]',
  QAD_toggle_el_print: '[data-cy="QuickAccessDropdown-toggle-element-print"]',
  QAD_toggle_el_printPreview: '[data-cy="QuickAccessDropdown-toggle-element-printPreview"]',

  FileDropdown: '[data-cy="FileDropdown"]',
  FileDropdown_close: '[data-cy="FileDropdown-close"]',
  FileDropdown_duo_save: '[data-cy="FileDropdown-duo-save"]',
  FileDropdown_duo_arrow_save: '[data-cy="FileDropdown-duo-save"]',
  FileDropdown_duo_print: '[data-cy="FileDropdown-duo-print"]',
  FileDropdown_duo_arrow_print: '[data-cy="FileDropdown-duo-print"]',
  FileDropdown_duo_set: '[data-cy="FileDropdown-duo-set"]',
  FileDropdown_duo_arrow_set: '[data-cy="FileDropdown-duo-set"]',

  FileDropdownMore: '[data-cy="FileDropdownMore"]',
  FileDropdownMore_Dropdown_any: '[data-cy^="FileDropdownMore-Dropdown"]',
  FileDropdownMore_Dropdown_save: '[data-cy="FileDropdownMore-Dropdown-save"]',
  FileDropdownMore_Dropdown_print: '[data-cy="FileDropdownMore-Dropdown-print"]',
  FileDropdownMore_Dropdown_set: '[data-cy="FileDropdownMore-Dropdown-set"]',

  RibbonControls_toggle_Ribbon: '[data-cy="RibbonControls-toggle-Ribbon"]',
  RibbonControls_toggle_FileDropdown: '[data-cy="RibbonControls-toggle-FileDropdown"]',
  RibbonControls_setTab_home: '[data-cy="RibbonControls-setTab-home"]',
  RibbonControls_setTab_view: '[data-cy="RibbonControls-setTab-view"]',

  RibbonItemContainer_Clipboard: '[data-cy="RibbonItemContainer-Clipboard"]',
  RibbonItemContainer_Image: '[data-cy="RibbonItemContainer-Image"]',
  RibbonItemContainer_Tools: '[data-cy="RibbonItemContainer-Tools"]',
  RibbonItemContainer_Shapes: '[data-cy="RibbonItemContainer-Shapes"]',
  RibbonItemContainer_Colors: '[data-cy="RibbonItemContainer-Colors"]',

  RibbonItemExpanded_Zoom: '[data-cy="RibbonItemExpanded-Zoom"]',
  RibbonItemExpanded_ShowOrHide: '[data-cy="RibbonItemExpanded-Show or hide"]',
  RibbonItemExpanded_Display: '[data-cy="RibbonItemExpanded-Display"]',
  
  BigButtonDuo_Brushes: '[data-cy="BigButtonDuo-Brushes"]',
  BigButton_Size: '[data-cy="BigButton-Size"]',
};