export default {
  Ribbon: '[data-cy="Ribbon"]',
  TopBar: '[data-cy="TopBar"]',
  
  QuickAccessToolbar: '[data-cy="QuickAccessToolbar"]',
  QAT_toggle_QAD: '[data-cy="QuickAccessToolbar-toggle-QuickAccessDropdown"]',
  QAT_el_save: '[data-cy="QuickAccessToolbar-element-save"]',
  QAT_el_undo: '[data-cy="QuickAccessToolbar-element-undo"]',
  QAT_el_redo: '[data-cy="QuickAccessToolbar-element-redo"]',
  QAT_el_open: '[data-cy="QuickAccessToolbar-element-open"]',
  QAT_el_email: '[data-cy="QuickAccessToolbar-element-email"]',
  QAT_el_newFile: '[data-cy="QuickAccessToolbar-element-newFile"]',
  QAT_el_print: '[data-cy="QuickAccessToolbar-element-print"]',
  QAT_el_printPreview: '[data-cy="QuickAccessToolbar-element-printPreview"]',
  
  QuickAccessDropdown: '[data-cy="QuickAccessDropdown"]',
  QAD_toggle_Ribbon: '[data-cy="QuickAccessDropdown-toggle-Ribbon"]',
  QAD_toggle_position: '[data-cy="QuickAccessDropdown-toggle-position"]',
  QAD_toggle_el_save: '[data-cy="QuickAccessDropdown-toggle-element-save"]',
  QAD_toggle_el_undo: '[data-cy="QuickAccessDropdown-toggle-element-undo"]',
  QAD_toggle_el_redo: '[data-cy="QuickAccessDropdown-toggle-element-redo"]',
  QAD_toggle_el_open: '[data-cy="QuickAccessDropdown-toggle-element-open"]',
  QAD_toggle_el_email: '[data-cy="QuickAccessDropdown-toggle-element-email"]',
  QAD_toggle_el_newFile: '[data-cy="QuickAccessDropdown-toggle-element-newFile"]',
  QAD_toggle_el_print: '[data-cy="QuickAccessDropdown-toggle-element-print"]',
  QAD_toggle_el_printPreview: '[data-cy="QuickAccessDropdown-toggle-element-printPreview"]',

  FileDropdown: '[data-cy="FileDropdown"]',
  FileDropdown_close: '[data-cy="FileDropdown-close"]',
  FileDropdown_duo_save: '[data-cy="FileDropdown-duo-save"]',
  FileDropdown_duo_arrow_save: '[data-cy="FileDropdown-duo-save"]',
  FileDropdown_duo_print: '[data-cy="FileDropdown-duo-print"]',
  FileDropdown_duo_arrow_print: '[data-cy="FileDropdown-duo-print"]',
  FileDropdown_duo_set: '[data-cy="FileDropdown-duo-set"]',
  FileDropdown_duo_arrow_set: '[data-cy="FileDropdown-duo-set"]',

  FileDropdownMore: '[data-cy="FileDropdownMore"]',
  FileDropdownMore_Dropdown_any: '[data-cy^="FileDropdownMore-Dropdown"]',
  FileDropdownMore_Dropdown_save: '[data-cy="FileDropdownMore-Dropdown-save"]',
  FileDropdownMore_Dropdown_print: '[data-cy="FileDropdownMore-Dropdown-print"]',
  FileDropdownMore_Dropdown_set: '[data-cy="FileDropdownMore-Dropdown-set"]',

  RibbonControls_toggle_Ribbon: '[data-cy="RibbonControls-toggle-Ribbon"]',
  RibbonControls_toggle_FileDropdown: '[data-cy="RibbonControls-toggle-FileDropdown"]',
  RibbonControls_setTab_home: '[data-cy="RibbonControls-setTab-home"]',
  RibbonControls_setTab_view: '[data-cy="RibbonControls-setTab-view"]',

  RibbonItemContainer_Clipboard: '[data-cy="RibbonItemContainer-Clipboard"]',
  RibbonItemContainer_Image: '[data-cy="RibbonItemContainer-Image"]',
  RibbonItemContainer_Tools: '[data-cy="RibbonItemContainer-Tools"]',
  RibbonItemContainer_Shapes: '[data-cy="RibbonItemContainer-Shapes"]',
  RibbonItemContainer_Colors: '[data-cy="RibbonItemContainer-Colors"]',

  RibbonItemExpanded_Shapes: '[data-cy="RibbonItemExpanded-Shapes"]',
  RibbonItemExpanded_Zoom: '[data-cy="RibbonItemExpanded-Zoom"]',
  RibbonItemExpanded_ShowOrHide: '[data-cy="RibbonItemExpanded-Show or hide"]',
  RibbonItemExpanded_Display: '[data-cy="RibbonItemExpanded-Display"]',
  
  Clipboard: '[data-cy="Clipboard"]',
  Clipboard_Paste_Dropdown: '[data-cy="Clipboard-Paste-Dropdown"]',
  Clipboard_buttons: '[data-cy="Clipboard-buttons"]',
  BigButtonDuo_bottom_Paste: '[data-cy="BigButtonDuo-bottom-Paste"]',

  Image: '[data-cy="Image"]',
  Image_Select_Dropdown: '[data-cy="Image-Select-Dropdown"]',
  Image_Rotate_Dropdown: '[data-cy="Image-Rotate-Dropdown"]',
  Image_buttons: '[data-cy="Image-buttons"]',
  Image_toggle_Rotate: '[data-cy="Image-toggle-Rotate"]',
  BigButtonDuo_bottom_Select: '[data-cy="BigButtonDuo-bottom-Select"]',
  Image_open_ResizeWindow: '[data-cy="Image-open-ResizeWindow"]',

  Tools: '[data-cy="Tools"]',

  Brushes_Dropdown: '[data-cy="Brushes-Dropdown"]',
  BigButtonDuo_Brushes: '[data-cy="BigButtonDuo-Brushes"]',
  BigButtonDuo_bottom_Brushes: '[data-cy="BigButtonDuo-bottom-Brushes"]',

  Shapes: '[data-cy="Shapes"]',
  Shapes_Outline_Dropdown: '[data-cy="Shapes-Outline-Dropdown"]',
  Shapes_Fill_Dropdown: '[data-cy="Shapes-Fill-Dropdown"]',
  Shapes_buttons: '[data-cy="Shapes-buttons"]',
  Shapes_toggle_Outline: '[data-cy="Shapes-toggle-Outline"]',
  Shapes_toggle_Fill: '[data-cy="Shapes-toggle-Fill"]',
  ShapesGrid: '[data-cy="ShapesGrid"]',
  ShapesGrid_Dropdown: '[data-cy="ShapesGrid-Dropdown"]',
  ShapesGrid_toggle_Dropdown: '[data-cy="ShapesGrid-toggle-Dropdown"]',

  Size_Dropdown: '[data-cy="Size-Dropdown"]',
  BigButton_Size: '[data-cy="BigButton-Size"]',

  Colors: '[data-cy="Colors"]',
  Colors_grid: '[data-cy="Colors-grid"]',
  BigButton_Edit_Colors: '[data-cy="BigButton-Edit-colors"]',
  BigButton_Color_1: '[data-cy="BigButton-Color-1"]',
  BigButton_Color_2: '[data-cy="BigButton-Color-2"]',

  ColorsWindow: '[data-cy="ColorsWindow"]',
  ColorsWindow_cancel: '[data-cy="ColorsWindow-cancel"]',
  ColorsWindow_confirm: '[data-cy="ColorsWindow-confirm"]',

  ColorPicker_field: '[data-cy="ColorPicker-field"]',
  ColorPicker_bar: '[data-cy="ColorPicker-bar"]',
  ColorPicker_input_h: '[data-cy="ColorPicker-input-h"]',
  ColorPicker_input_s: '[data-cy="ColorPicker-input-s"]',
  ColorPicker_input_l: '[data-cy="ColorPicker-input-l"]',
  ColorPicker_input_r: '[data-cy="ColorPicker-input-r"]',
  ColorPicker_input_g: '[data-cy="ColorPicker-input-g"]',
  ColorPicker_input_b: '[data-cy="ColorPicker-input-b"]',

  ResizeWindow: '[data-cy="ResizeWindow"]',
  ResizeWindow_confirm: '[data-cy="ResizeWindow-confirm"]',
  ResizeWindow_cancel: '[data-cy="ResizeWindow-cancel"]',
  ResizeWindow_radio_percentage: '[data-cy="ResizeWindow-radio-percentage"]',
  ResizeWindow_radio_pixels: '[data-cy="ResizeWindow-radio-pixels"]',
  ResizeWindow_input_resize_horizontal: '[data-cy="ResizeWindow-input-resize-horizontal"]',
  ResizeWindow_input_resize_vertical: '[data-cy="ResizeWindow-input-resize-vertical"]',
  ResizeWindow_input_skew_horizontal: '[data-cy="ResizeWindow-input-skew-horizontal"]',
  ResizeWindow_input_skew_vertical: '[data-cy="ResizeWindow-input-skew-vertical"]',
  ResizeWindow_checkbox_maintain: '[data-cy="ResizeWindow-checkbox-maintain"]',

  PromptWindow: '[data-cy="PromptWindow"]',

  WindowControls_InnerWindow_close: '[data-cy="WindowControls-InnerWindow-close"]',
  WindowControls_close: '[data-cy="WindowControls-close"]',
};